[project]
name = "backend"
version = "0.1.0"
description = "Программный модуль оценки производственных рисков на основе статистических моделей"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.9",
    "pymupdf>=1.27.2.3",
]

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "pytest>=9.0.3",
    "pytest-asyncio>=1.3.0",
]
