@startuml
skinparam dpi 150
skinparam shadowing false

entity "ПОДРАЗДЕЛЕНИЯ" as dept {
  идентификатор
  наименование
  тип
}

entity "ИНЦИДЕНТЫ" as inc {
  идентификатор
  дата
  идентификатор_подразделения
  тип_инцидента
  уровень_тяжести
  потерянные_дни
  описание
}

entity "ОТКАЗЫ_ОБОРУДОВАНИЯ" as fail {
  идентификатор
  дата
  идентификатор_подразделения
  тип_оборудования
  наименование
  наработка
  время_простоя
  причина_отказа
  стоимость_ремонта
}

entity "НАРУШЕНИЯ_ТБ" as viol {
  идентификатор
  дата
  идентификатор_подразделения
  тип_нарушения
  выявлено_при_аудите
  ответственный
}

entity "МЕДОСМОТРЫ" as med {
  идентификатор
  дата
  профессия
  идентификатор_подразделения
  результаты
  категория_заболевания
}

entity "ОЦЕНКИ_РИСКОВ" as risk {
  идентификатор
  метод
  наименование
  входные_параметры
  результат
  тип_источника
  идентификатор_источника
  дата_проведения
  автор
}

dept ||--o{ inc : "1:N"
dept ||--o{ fail : "1:N"
dept ||--o{ viol : "1:N"
dept ||--o{ med : "1:N"
@enduml
