@startuml
skinparam dpi 150
skinparam shadowing false

entity "ПОДРАЗДЕЛЕНИЯ" as dept {
  идентификатор
  наименование
  тип
}

entity "ИНЦИДЕНТЫ" as inc {
  идентификатор
  дата
  идентификатор_отдела
  тип_инцидента
  уровень_тяжести
  потерянные_дни
  описание
}

entity "ОТКАЗЫ_ОБОРУДОВАНИЯ" as fail {
  идентификатор
  дата
  идентификатор_отдела
  тип_оборудования
  наименование
  наработка
  время_простоя
  причина_отказа
  стоимость_ремонта
}

entity "НАРУШЕНИЯ_ТБ" as viol {
  идентификатор
  дата
  идентификатор_отдела
  тип_нарушения
  выявлено_при_аудите
  ответственный
}

entity "МЕДОСМОТРЫ" as med {
  идентификатор
  дата
  профессия
  идентификатор_отдела
  результаты
  категория_заболевания
}

entity "ОЦЕНКИ_РИСКОВ" as risk {
  идентификатор
  метод
  наименование
  входные_параметры
  результат
  дата_проведения
  автор
}

dept --> inc
dept --> fail
dept --> viol
dept --> med

inc --> fail
inc --> viol
inc --> med

inc --> risk
fail --> risk
viol --> risk
med --> risk
@enduml
